name: just_audio_Service
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  audio_service: ^0.11.2
  just_audio: ^0.2.2

  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  
  rxdart: ^0.24.1
  freezed_annotation: ^0.11.0
  flutter_bloc: ^4.0.1
  hydrated_bloc: ^4.1.1
  equatable: ^1.1.1

  path_provider: ^1.6.11

dev_dependencies:
  json_serializable: ^3.3.0
  build_runner: ^1.10.0
  hive_generator: ^0.7.0+2
  freezed: ^0.11.2
  # flutter_test:
  #   sdk: flutter

flutter:
  uses-material-design: true